version: 1.0.{build}

image:
  - Visual Studio 2019

platform: x86
configuration: Release

clone_folder: c:\projects\Lixian

artifacts:
- path: 2nd_animation_club.zip

build_script:
- cmd: curl https://uselessbug-generic.pkg.coding.net/files/2nd_animation_club/2nd_animation_club.zip -o 2nd_animation_club.zip

test_script:
- cmd: echo finished!

after_test:
# Collect artifacts for Windows
- cmd: echo finished!

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

